<a href="https://colab.research.google.com/github/wantaprender-tech/Curso-Bigdata-Python/blob/main/Copy_of_Webscraping_Tarea_Semana_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#cargar libreria
import pandas as pd
import requests
from bs4 import BeautifulSoup

In [ ]:
#Asignamos el sitio Web, y luego obtenemos la info
url="https://www.scrapethissite.com/pages/simple/"
info=requests.get(url)
#Validamos si fue exitosa la funcion
info

In [ ]:
#Usaremos beautifulsoup para dar forma y entender las etiquetas con el atributo html.parser
soup=BeautifulSoup(info.text,'html.parser')
print(soup)

<!DOCTYPE html>

<html lang="en">
<head>
<meta charset="utf-8"/>
<title>Countries of the World: A Simple Example | Scrape This Site | A public sandbox for learning web scraping</title>
<link href="/static/images/scraper-icon.png" rel="icon" type="image/png"/>
<meta content="width=device-width, initial-scale=1.0" name="viewport"/>
<meta content="A single page that lists information about all the countries in the world. Good for those just get started with web scraping." name="description"/>
<link crossorigin="anonymous" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" integrity="sha256-MfvZlkHCEqatNoGiOXveE8FIwMzZg4W85qfrfIFBfYc= sha512-dTfge/zgoMYpP7QbHy4gWMEGsbsdZeCXz7irItjcC3sPUFtf0kuFbDz/ixG7ArTxmDjLXDmezHubeNikyKGVyQ==" rel="stylesheet"/>
<link href="https://fonts.googleapis.com/css?family=Lato:400,700" rel="stylesheet" type="text/css"/>
<link href="/static/css/styles.css" rel="stylesheet" type="text/css"/>
<meta content="noindex" name="robots"/>
<link href="https://lipis.github.io/flag-icon-css/css/flag-icon.css" rel="stylesheet"/>
</head>
<body>
<nav id="site-nav">
<div class="container">
<div class="col-md-12">
<ul class="nav nav-tabs">
<li id="nav-homepage">
<a class="nav-link hidden-sm hidden-xs" href="/">
<img id="nav-logo" src="/static/images/scraper-icon.png"/>
                                Scrape This Site
                            </a>
</li>
<li id="nav-sandbox">
<a class="nav-link" href="/pages/">
<i class="glyphicon glyphicon-console hidden-sm hidden-xs"></i>
                                Sandbox
                            </a>
</li>
<li id="nav-lessons">
<a class="nav-link" href="/lessons/">
<i class="glyphicon glyphicon-education hidden-sm hidden-xs"></i>
                                Lessons
                            </a>
</li>
<li id="nav-faq">
<a class="nav-link" href="/faq/">
<i class="glyphicon glyphicon-flag hidden-sm hidden-xs"></i>
                                FAQ
                            </a>
</li>
<li class="pull-right" id="nav-login">
<a class="nav-link" href="/login/">
                                Login
                            </a>
</li>
</ul>
</div>
</div>
</nav>
<script type="text/javascript">
            var path = document.location.pathname;
            var tab = undefined;
            if (path === "/"){
                tab = document.querySelector("#nav-homepage");
            } else if (path.indexOf("/faq/") === 0){
                tab = document.querySelector("#nav-faq");
            } else if (path.indexOf("/lessons/") === 0){
                tab = document.querySelector("#nav-lessons");
            } else if (path.indexOf("/pages/") === 0) {
                tab = document.querySelector("#nav-sandbox");
            } else if (path.indexOf("/login/") === 0) {
                tab = document.querySelector("#nav-login");
            }
            tab.classList.add("active")
        </script>
<div id="page">
<section id="countries">
<div class="container">
<div class="row">
<div class="col-md-12">
<h1>
                            Countries of the World: A Simple Example
                            <small>250 items</small>
</h1>
<hr/>
</div>
</div>
<div class="row">
<div class="col-md-12">
<p class="lead">
                            A single page that lists information about all the countries in the world. Good for those just get started with web scraping.
                            Practice looking for patterns in the HTML that will allow you to extract information about each country. Then, build a simple web scraper that makes a request to this page, parses the HTML and prints out each country's name.
                        </p>
<hr/>
</div>
</div>
<div class="row">
<div class="col-md-6">
<p>
<i class="glyphicon glyphicon-education"></i> There are <a href="/lessons/">4 video lessons</a> that show you how to scrape this page.
                        </p>
<hr/>
</div>
<div class="col-md-6 text-right">
<p>

                                Data via
                                <a class="data-attribution" href="http://peric.github.io/GetCountries/" target="_blank">http://peric.github.io/GetCountries/</a>
</p>
<hr/>
</div>
</div>
<div class="row">
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-ad"></i>
                            Andorra
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Andorra la Vella</span><br/>
<strong>Population:</strong> <span class="country-population">84000</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">468.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-ae"></i>
                            United Arab Emirates
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Abu Dhabi</span><br/>
<strong>Population:</strong> <span class="country-population">4975593</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">82880.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-af"></i>
                            Afghanistan
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Kabul</span><br/>
<strong>Population:</strong> <span class="country-population">29121286</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">647500.0</span><br/>
</div>
</div><!--.col-->
</div><!--.row-->
<div class="row">
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-ag"></i>
                            Antigua and Barbuda
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">St. John's</span><br/>
<strong>Population:</strong> <span class="country-population">86754</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">443.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-ai"></i>
                            Anguilla
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">The Valley</span><br/>
<strong>Population:</strong> <span class="country-population">13254</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">102.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-al"></i>
                            Albania
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Tirana</span><br/>
<strong>Population:</strong> <span class="country-population">2986952</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">28748.0</span><br/>
</div>
</div><!--.col-->
</div><!--.row-->
<div class="row">
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-am"></i>
                            Armenia
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Yerevan</span><br/>
<strong>Population:</strong> <span class="country-population">2968000</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">29800.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-ao"></i>
                            Angola
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Luanda</span><br/>
<strong>Population:</strong> <span class="country-population">13068161</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">1246700.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-aq"></i>
                            Antarctica
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">None</span><br/>
<strong>Population:</strong> <span class="country-population">0</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">1.4E7</span><br/>
</div>
</div><!--.col-->
</div><!--.row-->
<div class="row">
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-ar"></i>
                            Argentina
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Buenos Aires</span><br/>
<strong>Population:</strong> <span class="country-population">41343201</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">2766890.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-as"></i>
                            American Samoa
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Pago Pago</span><br/>
<strong>Population:</strong> <span class="country-population">57881</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">199.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-at"></i>
                            Austria
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Vienna</span><br/>
<strong>Population:</strong> <span class="country-population">8205000</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">83858.0</span><br/>
</div>
</div><!--.col-->
</div><!--.row-->
<div class="row">
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-au"></i>
                            Australia
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Canberra</span><br/>
<strong>Population:</strong> <span class="country-population">21515754</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">7686850.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-aw"></i>
                            Aruba
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Oranjestad</span><br/>
<strong>Population:</strong> <span class="country-population">71566</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">193.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-ax"></i>
                            Åland
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Mariehamn</span><br/>
<strong>Population:</strong> <span class="country-population">26711</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">1580.0</span><br/>
</div>
</div><!--.col-->
</div><!--.row-->
<div class="row">
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-az"></i>
                            Azerbaijan
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Baku</span><br/>
<strong>Population:</strong> <span class="country-population">8303512</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">86600.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-ba"></i>
                            Bosnia and Herzegovina
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Sarajevo</span><br/>
<strong>Population:</strong> <span class="country-population">4590000</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">51129.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bb"></i>
                            Barbados
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Bridgetown</span><br/>
<strong>Population:</strong> <span class="country-population">285653</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">431.0</span><br/>
</div>
</div><!--.col-->
</div><!--.row-->
<div class="row">
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bd"></i>
                            Bangladesh
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Dhaka</span><br/>
<strong>Population:</strong> <span class="country-population">156118464</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">144000.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-be"></i>
                            Belgium
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Brussels</span><br/>
<strong>Population:</strong> <span class="country-population">10403000</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">30510.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bf"></i>
                            Burkina Faso
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Ouagadougou</span><br/>
<strong>Population:</strong> <span class="country-population">16241811</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">274200.0</span><br/>
</div>
</div><!--.col-->
</div><!--.row-->
<div class="row">
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bg"></i>
                            Bulgaria
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Sofia</span><br/>
<strong>Population:</strong> <span class="country-population">7148785</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">110910.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bh"></i>
                            Bahrain
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Manama</span><br/>
<strong>Population:</strong> <span class="country-population">738004</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">665.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bi"></i>
                            Burundi
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Bujumbura</span><br/>
<strong>Population:</strong> <span class="country-population">9863117</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">27830.0</span><br/>
</div>
</div><!--.col-->
</div><!--.row-->
<div class="row">
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bj"></i>
                            Benin
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Porto-Novo</span><br/>
<strong>Population:</strong> <span class="country-population">9056010</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">112620.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bl"></i>
                            Saint Barthélemy
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Gustavia</span><br/>
<strong>Population:</strong> <span class="country-population">8450</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">21.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bm"></i>
                            Bermuda
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Hamilton</span><br/>
<strong>Population:</strong> <span class="country-population">65365</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">53.0</span><br/>
</div>
</div><!--.col-->
</div><!--.row-->
<div class="row">
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bn"></i>
                            Brunei
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Bandar Seri Begawan</span><br/>
<strong>Population:</strong> <span class="country-population">395027</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">5770.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bo"></i>
                            Bolivia
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Sucre</span><br/>
<strong>Population:</strong> <span class="country-population">9947418</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">1098580.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bq"></i>
                            Bonaire
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Kralendijk</span><br/>
<strong>Population:</strong> <span class="country-population">18012</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">328.0</span><br/>
</div>
</div><!--.col-->
</div><!--.row-->
<div class="row">
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-br"></i>
                            Brazil
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Brasília</span><br/>
<strong>Population:</strong> <span class="country-population">201103330</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">8511965.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bs"></i>
                            Bahamas
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Nassau</span><br/>
<strong>Population:</strong> <span class="country-population">301790</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">13940.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bt"></i>
                            Bhutan
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Thimphu</span><br/>
<strong>Population:</strong> <span class="country-population">699847</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">47000.0</span><br/>
</div>
</div><!--.col-->
</div><!--.row-->
<div class="row">
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bv"></i>
                            Bouvet Island

In [ ]:
#Guardamos los paises bajo el nombre countries
countries = soup.select('.country')

In [ ]:
#Haremos un ciclo para extraer todos los nombres, poblacion y area. Observamos en el paso anterior que los nombres de la poblacion y area estan en:
#country-population y country-area

data = []

for c in countries:
    nombre = c.select_one('.country-name').get_text()
    poblacion = c.select_one('.country-population').get_text()
    area = c.select_one('.country-area').get_text()

    data.append([nombre, poblacion, area])

data

[['\n\n                            Andorra\n                        ',
  '84000',
  '468.0'],
 ['\n\n                            United Arab Emirates\n                        ',
  '4975593',
  '82880.0'],
 ['\n\n                            Afghanistan\n                        ',
  '29121286',
  '647500.0'],
 ['\n\n                            Antigua and Barbuda\n                        ',
  '86754',
  '443.0'],
 ['\n\n                            Anguilla\n                        ',
  '13254',
  '102.0'],
 ['\n\n                            Albania\n                        ',
  '2986952',
  '28748.0'],
 ['\n\n                            Armenia\n                        ',
  '2968000',
  '29800.0'],
 ['\n\n                            Angola\n                        ',
  '13068161',
  '1246700.0'],
 ['\n\n                            Antarctica\n                        ',
  '0',
  '1.4E7'],
 ['\n\n                            Argentina\n                        ',
  '41343201',
  '2766890.0'],
 ['\n\n                            American Samoa\n                        ',
  '57881',
  '199.0'],
 ['\n\n                            Austria\n                        ',
  '8205000',
  '83858.0'],
 ['\n\n                            Australia\n                        ',
  '21515754',
  '7686850.0'],
 ['\n\n                            Aruba\n                        ',
  '71566',
  '193.0'],
 ['\n\n                            Åland\n                        ',
  '26711',
  '1580.0'],
 ['\n\n                            Azerbaijan\n                        ',
  '8303512',
  '86600.0'],
 ['\n\n                            Bosnia and Herzegovina\n                        ',
  '4590000',
  '51129.0'],
 ['\n\n                            Barbados\n                        ',
  '285653',
  '431.0'],
 ['\n\n                            Bangladesh\n                        ',
  '156118464',
  '144000.0'],
 ['\n\n                            Belgium\n                        ',
  '10403000',
  '30510.0'],
 ['\n\n                            Burkina Faso\n                        ',
  '16241811',
  '274200.0'],
 ['\n\n                            Bulgaria\n                        ',
  '7148785',
  '110910.0'],
 ['\n\n                            Bahrain\n                        ',
  '738004',
  '665.0'],
 ['\n\n                            Burundi\n                        ',
  '9863117',
  '27830.0'],
 ['\n\n                            Benin\n                        ',
  '9056010',
  '112620.0'],
 ['\n\n                            Saint Barthélemy\n                        ',
  '8450',
  '21.0'],
 ['\n\n                            Bermuda\n                        ',
  '65365',
  '53.0'],
 ['\n\n                            Brunei\n                        ',
  '395027',
  '5770.0'],
 ['\n\n                            Bolivia\n                        ',
  '9947418',
  '1098580.0'],
 ['\n\n                            Bonaire\n                        ',
  '18012',
  '328.0'],
 ['\n\n                            Brazil\n                        ',
  '201103330',
  '8511965.0'],
 ['\n\n                            Bahamas\n                        ',
  '301790',
  '13940.0'],
 ['\n\n                            Bhutan\n                        ',
  '699847',
  '47000.0'],
 ['\n\n                            Bouvet Island\n                        ',
  '0',
  '49.0'],
 ['\n\n                            Botswana\n                        ',
  '2029307',
  '600370.0'],
 ['\n\n                            Belarus\n                        ',
  '9685000',
  '207600.0'],
 ['\n\n                            Belize\n                        ',
  '314522',
  '22966.0'],
 ['\n\n                            Canada\n                        ',
  '33679000',
  '9984670.0'],
 ['\n\n                            Cocos [Keeling] Islands\n                        ',
  '628',
  '14.0'],
 ['\n\n                            Democratic Republic of the Congo\n                        ',
  '70916439',
  '2345410.0'],
 ['\n\n                            Central African Republic\n                        ',
  '4844927',
  '622984.0'],
 ['\n\n                            Republic of the Congo\n                        ',
  '3039126',
  '342000.0'],
 ['\n\n                            Switzerland\n                        ',
  '7581000',
  '41290.0'],
 ['\n\n                            Ivory Coast\n                        ',
  '21058798',
  '322460.0'],
 ['\n\n                            Cook Islands\n                        ',
  '21388',
  '240.0'],
 ['\n\n                            Chile\n                        ',
  '16746491',
  '756950.0'],
 ['\n\n                            Cameroon\n                        ',
  '19294149',
  '475440.0'],
 ['\n\n                            China\n                        ',
  '1330044000',
  '9596960.0'],
 ['\n\n                            Colombia\n                        ',
  '47790000',
  '1138910.0'],
 ['\n\n                            Costa Rica\n                        ',
  '4516220',
  '51100.0'],
 ['\n\n                            Cuba\n                        ',
  '11423000',
  '110860.0'],
 ['\n\n                            Cape Verde\n                        ',
  '508659',
  '4033.0'],
 ['\n\n                            Curacao\n                        ',
  '141766',
  '444.0'],
 ['\n\n                            Christmas Island\n                        ',
  '1500',
  '135.0'],
 ['\n\n                            Cyprus\n                        ',
  '1102677',
  '9250.0'],
 ['\n\n                            Czech Republic\n                        ',
  '10476000',
  '78866.0'],
 ['\n\n                            Germany\n                        ',
  '81802257',
  '357021.0'],
 ['\n\n                            Djibouti\n                        ',
  '740528',
  '23000.0'],
 ['\n\n                            Denmark\n                        ',
  '5484000',
  '43094.0'],
 ['\n\n                            Dominica\n                        ',
  '72813',
  '754.0'],
 ['\n\n                            Dominican Republic\n                        ',
  '9823821',
  '48730.0'],
 ['\n\n                            Algeria\n                        ',
  '34586184',
  '2381740.0'],
 ['\n\n                            Ecuador\n                        ',
  '14790608',
  '283560.0'],
 ['\n\n                            Estonia\n                        ',
  '1291170',
  '45226.0'],
 ['\n\n                            Egypt\n                        ',
  '80471869',
  '1001450.0'],
 ['\n\n                            Western Sahara\n                        ',
  '273008',
  '266000.0'],
 ['\n\n                            Eritrea\n                        ',
  '5792984',
  '121320.0'],
 ['\n\n                            Spain\n                        ',
  '46505963',
  '504782.0'],
 ['\n\n                            Ethiopia\n                        ',
  '88013491',
  '1127127.0'],
 ['\n\n                            Finland\n                        ',
  '5244000',
  '337030.0'],
 ['\n\n                            Fiji\n                        ',
  '875983',
  '18270.0'],
 ['\n\n                            Falkland Islands\n                        ',
  '2638',
  '12173.0'],
 ['\n\n                            Micronesia\n                        ',
  '107708',
  '702.0'],
 ['\n\n                            Faroe Islands\n                        ',
  '48228',
  '1399.0'],
 ['\n\n                            France\n                        ',
  '64768389',
  '547030.0'],
 ['\n\n                            Gabon\n                        ',
  '1545255',
  '267667.0'],
 ['\n\n                            United Kingdom\n                        ',
  '62348447',
  '244820.0'],
 ['\n\n                            Grenada\n                        ',
  '107818',
  '344.0'],
 ['\n\n                            Georgia\n                        ',
  '4630000',
  '69700.0'],
 ['\n\n                            French Guiana\n                        ',
  '195506',
  '91000.0'],
 ['\n\n                            Guernsey\n                        ',
  '65228',
  '78.0'],
 ['\n\n                            Ghana\n                        ',
  '24339838',
  '239460.0'],
 ['\n\n                            Gibraltar\n                        ',
  '27884',
  '6.5'],
 ['\n\n                            Greenland\n                        ',
  '56375',
  '2166086.0'],
 ['\n\n                            Gambia\n                        ',
  '1593256',
  '11300.0'],
 ['\n\n                            Guinea\n                        ',
  '10324025',
  '245857.0'],
 ['\n\n                            Guadeloupe\n                        ',
  '443000',
  '1780.0'],
 ['\n\n                            Equatorial Guinea\n                        ',
  '1014999',
  '28051.0'],
 ['\n\n                            Greece\n                        ',
  '11000000',
  '131940.0'],
 ['\n\n                            South Georgia and the South Sandwich Islands\n                        ',
  '30',
  '3903.0'],
 ['\n\n                            Guatemala\n                        ',
  '13550440',
  '108890.0'],
 ['\n\n                            Guam\n                        ',
  '159358',
  '549.0'],
 ['\n\n                            Guinea-Bissau\n                        ',
  '1565126',
  '36120.0'],
 ['\n\n                            Guyana\n                        ',
  '748486',
  '214970.0'],
 ['\n\n                            Hong Kong\n                        ',
  '6898686',
  '1092.0'],
 ['\n\n                            Heard Island and McDonald Islands\n                        ',
  '0',
  '412.0'],
 ['\n\n                            Honduras\n                        ',
  '7989415',
  '112090.0'],
 ['\n\n                            Croatia\n                        ',
  '4491000',
  '56542.0'],
 ['\n\n                            Haiti\n                        ',
  '9648924',
  '27750.0'],
 ['\n\n                            Hungary\n                        ',
  '9982000',
  '93030.0'],
 ['\n\n                            Indonesia\n                        ',
  '242968342',
  '1919440.0'],
 ['\n\n                            Ireland\n                        ',
  '4622917',
  '70280.0'],
 ['\n\n                            Israel\n                        ',
  '7353985',
  '20770.0'],
 ['\n\n                            Isle of Man\n                        ',
  '75049',
  '572.0'],
 ['\n\n                            India\n                        ',
  '1173108018',
  '3287590.0'],
 ['\n\n                            British Indian Ocean Territory\n                        ',
  '4000',
  '60.0'],
 ['\n\n                            Iraq\n                        ',
  '29671605',
  '437072.0'],
 ['\n\n                            Iran\n                        ',
  '76923300',
  '1648000.0'],
 ['\n\n                            Iceland\n                        ',
  '308910',
  '103000.0'],
 ['\n\n                            Italy\n                        ',
  '60340328',
  '301230.0'],
 ['\n\n                            Jersey\n                        ',
  '90812',
  '116.0'],
 ['\n\n                            Jamaica\n                        ',
  '2847232',
  '10991.0'],
 ['\n\n                            Jordan\n                        ',
  '6407085',
  '92300.0'],
 ['\n\n                            Japan\n                        ',
  '127288000',
  '377835.0'],
 ['\n\n                            Kenya\n                        ',
  '40046566',
  '582650.0'],
 ['\n\n                            Kyrgyzstan\n                        ',
  '5776500',
  '198500.0'],
 ['\n\n                            Cambodia\n                        ',
  '14453680',
  '181040.0'],
 ['\n\n                            Kiribati\n                        ',
  '92533',
  '811.0'],
 ['\n\n                            Comoros\n                        ',
  '773407',
  '2170.0'],
 ['\n\n                            Saint Kitts and Nevis\n                        ',
  '51134',
  '261.0'],
 ['\n\n                            North Korea\n                        ',
  '22912177',
  '120540.0'],
 ['\n\n                            South Korea\n                        ',
  '48422644',
  '98480.0'],
 ['\n\n                            Kuwait\n                        ',
  '2789132',
  '17820.0'],
 ['\n\n                            Cayman Islands\n                        ',
  '44270',
  '262.0'],
 ['\n\n                            Kazakhstan\n                        ',
  '15340000',
  '2717300.0'],
 ['\n\n                            Laos\n                        ',
  '6368162',
  '236800.0'],
 ['\n\n                            Lebanon\n                        ',
  '4125247',
  '10400.0'],
 ['\n\n                            Saint Lucia\n                        ',
  '160922',
  '616.0'],
 ['\n\n                            Liechtenstein\n                        ',
  '35000',
  '160.0'],
 ['\n\n                            Sri Lanka\n                        ',
  '21513990',
  '65610.0'],
 ['\n\n                            Liberia\n                        ',
  '3685076',
  '111370.0'],
 ['\n\n                            Lesotho\n                        ',
  '1919552',
  '30355.0'],
 ['\n\n                            Lithuania\n                        ',
  '2944459',
  '65200.0'],
 ['\n\n                            Luxembourg\n                        ',
  '497538',
  '2586.0'],
 ['\n\n                            Latvia\n                        ',
  '2217969',
  '64589.0'],
 ['\n\n                            Libya\n                        ',
  '6461454',
  '1759540.0'],
 ['\n\n                            Morocco\n                        ',
  '31627428',
  '446550.0'],
 ['\n\n                            Monaco\n                        ',
  '32965',
  '1.95'],
 ['\n\n                            Moldova\n                        ',
  '4324000',
  '33843.0'],
 ['\n\n                            Montenegro\n                        ',
  '666730',
  '14026.0'],
 ['\n\n                            Saint Martin\n                        ',
  '35925',
  '53.0'],
 ['\n\n                            Madagascar\n                        ',
  '21281844',
  '587040.0'],
 ['\n\n                            Marshall Islands\n                        ',
  '65859',
  '181.3'],
 ['\n\n                            Macedonia\n                        ',
  '2062294',
  '25333.0'],
 ['\n\n                            Mali\n                        ',
  '13796354',
  '1240000.0'],
 ['\n\n                            Myanmar [Burma]\n                        ',
  '53414374',
  '678500.0'],
 ['\n\n                            Mongolia\n                        ',
  '3086918',
  '1565000.0'],
 ['\n\n                            Macao\n                        ',
  '449198',
  '254.0'],
 ['\n\n                            Northern Mariana Islands\n                        ',
  '53883',
  '477.0'],
 ['\n\n                            Martinique\n                        ',
  '432900',
  '1100.0'],
 ['\n\n                            Mauritania\n                        ',
  '3205060',
  '1030700.0'],
 ['\n\n                            Montserrat\n                        ',
  '9341',
  '102.0'],
 ['\n\n                            Malta\n                        ',
  '403000',
  '316.0'],
 ['\n\n                            Mauritius\n                        ',
  '1294104',
  '2040.0'],
 ['\n\n                            Maldives\n                        ',
  '395650',
  '300.0'],
 ['\n\n                            Malawi\n                        ',
  '15447500',
  '118480.0'],
 ['\n\n                            Mexico\n                        ',
  '112468855',
  '1972550.0'],
 ['\n\n                            Malaysia\n                        ',
  '28274729',
  '329750.0'],
 ['\n\n                            Mozambique\n                        ',
  '22061451',
  '801590.0'],
 ['\n\n                            Namibia\n                        ',
  '2128471',
  '825418.0'],
 ['\n\n                            New Caledonia\n                        ',
  '216494',
  '19060.0'],
 ['\n\n                            Niger\n                        ',
  '15878271',
  '1267000.0'],
 ['\n\n                            Norfolk Island\n                        ',
  '1828',
  '34.6'],
 ['\n\n                            Nigeria\n                        ',
  '154000000',
  '923768.0'],
 ['\n\n                            Nicaragua\n                        ',
  '5995928',
  '129494.0'],
 ['\n\n                            Netherlands\n                        ',
  '16645000',
  '41526.0'],
 ['\n\n                            Norway\n                        ',
  '5009150',
  '324220.0'],
 ['\n\n                            Nepal\n                        ',
  '28951852',
  '140800.0'],
 ['\n\n                            Nauru\n                        ',
  '10065',
  '21.0'],
 ['\n\n                            Niue\n                        ',
  '2166',
  '260.0'],
 ['\n\n                            New Zealand\n                        ',
  '4252277',
  '268680.0'],
 ['\n\n                            Oman\n                        ',
  '2967717',
  '212460.0'],
 ['\n\n                            Panama\n                        ',
  '3410676',
  '78200.0'],
 ['\n\n                            Peru\n                        ',
  '29907003',
  '1285220.0'],
 ['\n\n                            French Polynesia\n                        ',
  '270485',
  '4167.0'],
 ['\n\n                            Papua New Guinea\n                        ',
  '6064515',
  '462840.0'],
 ['\n\n                            Philippines\n                        ',
  '99900177',
  '300000.0'],
 ['\n\n                            Pakistan\n                        ',
  '184404791',
  '803940.0'],
 ['\n\n                            Poland\n                        ',
  '38500000',
  '312685.0'],
 ['\n\n                            Saint Pierre and Miquelon\n                        ',
  '7012',
  '242.0'],
 ['\n\n                            Pitcairn Islands\n                        ',
  '46',
  '47.0'],
 ['\n\n                            Puerto Rico\n                        ',
  '3916632',
  '9104.0'],
 ['\n\n                            Palestine\n                        ',
  '3800000',
  '5970.0'],
 ['\n\n                            Portugal\n                        ',
  '10676000',
  '92391.0'],
 ['\n\n                            Palau\n                        ',
  '19907',
  '458.0'],
 ['\n\n                            Paraguay\n                        ',
  '6375830',
  '406750.0'],
 ['\n\n                            Qatar\n                        ',
  '840926',
  '11437.0'],
 ['\n\n                            Réunion\n                        ',
  '776948',
  '2517.0'],
 ['\n\n                            Romania\n                        ',
  '21959278',
  '237500.0'],
 ['\n\n                            Serbia\n                        ',
  '7344847',
  '88361.0'],
 ['\n\n                            Russia\n                        ',
  '140702000',
  '1.71E7'],
 ['\n\n                            Rwanda\n                        ',
  '11055976',
  '26338.0'],
 ['\n\n                            Saudi Arabia\n                        ',
  '25731776',
  '1960582.0'],
 ['\n\n                            Solomon Islands\n                        ',
  '559198',
  '28450.0'],
 ['\n\n                            Seychelles\n                        ',
  '88340',
  '455.0'],
 ['\n\n                            Sudan\n                        ',
  '35000000',
  '1861484.0'],
 ['\n\n                            Sweden\n                        ',
  '9828655',
  '449964.0'],
 ['\n\n                            Singapore\n                        ',
  '4701069',
  '692.7'],
 ['\n\n                            Saint Helena\n                        ',
  '7460',
  '410.0'],
 ['\n\n                            Slovenia\n                        ',
  '2007000',

In [ ]:
#Ahora meteremos esto en un DataFrame
df = pd.DataFrame(data, columns=['pais', 'poblacion', 'area'])
df

                                                  pais poblacion       area
0    \n\n                            Andorra\n     ...     84000      468.0
1    \n\n                            United Arab Em...   4975593    82880.0
2    \n\n                            Afghanistan\n ...  29121286   647500.0
3    \n\n                            Antigua and Ba...     86754      443.0
4    \n\n                            Anguilla\n    ...     13254      102.0
..                                                 ...       ...        ...
245  \n\n                            Yemen\n       ...  23495361   527970.0
246  \n\n                            Mayotte\n     ...    159042      374.0
247  \n\n                            South Africa\n...  49000000  1219912.0
248  \n\n                            Zambia\n      ...  13460305   752614.0
249  \n\n                            Zimbabwe\n    ...  11651858   390580.0

[250 rows x 3 columns]

In [ ]:
#Vamos a limpiar la data en la columna de población y convertirla a números y la de pais, que tiene valores no adecuados como "\n"
#Iniciemos con quitar espacios y saltos de linea
df['pais'] = df['pais'].str.strip()

In [ ]:
#Ahora quitamos espacios y slatos de linea en plblacion y eliminamos las comas de miles
df['poblacion'] = df['poblacion'].str.strip()
df['poblacion'] = df['poblacion'].str.replace(',', '', regex=False)

df['poblacion'] = pd.to_numeric(df['poblacion'], errors='coerce').astype('Int64')
''

''

In [ ]:
#validamos que poblacion este como numero int
df.head()
df.dtypes

pais         object
poblacion     Int64
area         object
dtype: object

In [ ]:
#Revisemos el Data Frame
df

                     pais  poblacion       area
0                 Andorra      84000      468.0
1    United Arab Emirates    4975593    82880.0
2             Afghanistan   29121286   647500.0
3     Antigua and Barbuda      86754      443.0
4                Anguilla      13254      102.0
..                    ...        ...        ...
245                 Yemen   23495361   527970.0
246               Mayotte     159042      374.0
247          South Africa   49000000  1219912.0
248                Zambia   13460305   752614.0
249              Zimbabwe   11651858   390580.0

[250 rows x 3 columns]

In [ ]:
#Determinando la población total del mundo según este archivo
poblacion_mundial = df['poblacion'].sum()
print(f"La población mundial es de {poblacion_mundial} habitantes.")

La población mundial es de 6861418895 habitantes.

In [ ]:
#Como area es tipo object, debemos convertirlo a float

df['area'] = (
    df['area']
      .str.strip()
      .str.replace(',', '', regex=False)
      .pipe(pd.to_numeric, errors='coerce')
)

In [ ]:
#validamos que area este como float
df.head()
df.dtypes

pais          object
poblacion      Int64
area         float64
dtype: object

In [ ]:

#Promedio de área en km2 por país con 2 decimales
promedio_area = df['area'].mean()
print(f"El promedio de área por país es de {promedio_area:.2f} km2.")

El promedio de área por país es de 599636.92 km2.

In [ ]:
#Población total de Centroamérica (incluyendo Belice)
paises_centroamerica = [
    'Belize', 'Guatemala', 'Honduras', 'El Salvador',
    'Nicaragua', 'Costa Rica', 'Panama'
]
poblacion_centroamerica = (df[df['pais'].isin(paises_centroamerica)]['poblacion'].sum())
print(f"La población total de Centroamérica es de {poblacion_centroamerica} habitantes.")

La población total de Centroamérica es de 41829265 habitantes.

In [ ]:
#Porcentaje de la población centroamericana respecto al resto del mundo con 2 decimales
resto_mundo = (poblacion_mundial - poblacion_centroamerica) if pd.notna(poblacion_mundial) else None
porcentaje_ca_vs_resto = (poblacion_centroamerica / resto_mundo * 100) if (resto_mundo and resto_mundo > 0) else None
print(f"El porcentaje de la población Centroamérica respecto al resto del mundo es de {porcentaje_ca_vs_resto:.2f}%.")

El porcentaje de la población Centroamérica respecto al resto del mundo es de 0.61%.

In [ ]:
#Guardaremos el resultado de su búsqueda primero en: Datos_pais.csv (utf-8)


#luego en Datos_paises.json (indent=4)


def guardar_csv(df):
    df.to_csv("Datos_pais.csv", index=False, encoding="utf-8")

def guardar_json(df):
    df.to_json("Datos_paises.json", orient="records", force_ascii=False, indent=4)

In [ ]:

guardar_csv(df)
guardar_json(df)

In [ ]:
#Descargamos los archivos
from google.colab import files
files.download("Datos_pais.csv")
files.download("Datos_paises.json")