In [3]:
import pandas as pd

In [4]:
#cargando archivo csv
url_csv="https://raw.githubusercontent.com/cienciadedatos/datos-de-miercoles/master/datos/2019/2019-08-07/felicidad.csv"
df_csv=pd.read_csv(url_csv)

In [5]:
#Mostrando los primeros 6 registros
df_csv.head(6)

,pais,anio,escalera_vida,log_pib,soporte_social,expectativa_vida,libertad,generosidad,percepcion_corrupcion,afecto_positivo,afecto_negativo,confianza,calidad_democracia,calidad_entrega,de_escalera_pais_anio,gini_banco_mundial,gini_banco_mundial_promedio
0,Afghanistán,2008,3.723590,7.168690,0.450662,50.799999,0.718114,0.177889,0.881686,0.517637,0.258195,0.612072,-1.929690,-1.655084,1.774662,NaN,NaN
1,Afghanistán,2009,4.401778,7.333790,0.552308,51.200001,0.678896,0.200178,0.850035,0.583926,0.237092,0.611545,-2.044093,-1.635025,1.722688,NaN,NaN
2,Afghanistán,2010,4.758381,7.386629,0.539075,51.599998,0.600127,0.134353,0.706766,0.618265,0.275324,0.299357,-1.991810,-1.617176,1.878622,NaN,NaN
3,Afghanistán,2011,3.831719,7.415019,0.521104,51.919998,0.495901,0.172137,0.731109,0.611387,0.267175,0.307386,-1.919018,-1.616221,1.785360,NaN,NaN
4,Afghanistán,2012,3.782938,7.517126,0.520637,52.240002,0.530935,0.244273,0.775620,0.710385,0.267919,0.435440,-1.842996,-1.404078,1.798283,NaN,NaN
5,Afghanistán,2013,3.572100,7.522238,0.483552,52.560001,0.577955,0.070403,0.823204,0.620585,0.273328,0.482847,-1.879709,-1.403036,1.223690,NaN,NaN

In [6]:
#Mostrando la informacion del archivo
df_csv.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1704 entries, 0 to 1703
Data columns (total 17 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   pais                         1704 non-null   object
 1   anio                         1704 non-null   int64
 2   escalera_vida                1704 non-null   float64
 3   log_pib                      1676 non-null   float64
 4   soporte_social               1691 non-null   float64
 5   expectativa_vida             1676 non-null   float64
 6   libertad                     1675 non-null   float64
 7   generosidad                  1622 non-null   float64
 8   percepcion_corrupcion        1608 non-null   float64
 9   afecto_positivo              1685 non-null   float64
 10  afecto_negativo              1691 non-null   float64
 11  confianza                    1530 non-null   float64
 12  calidad_democracia           1558 non-null   float64
 13  calidad_entrega              1559 non-null   float64
 14  de_escalera_pais_anio        1704 non-null   float64
 15  gini_banco_mundial           643 non-null    float64
 16  gini_banco_mundial_promedio  1502 non-null   float64
dtypes: float64(15), int64(1), object(1)
memory usage: 226.4+ KB

In [7]:
#Tamaño del archivo
df_csv.shape

(1704, 17)

In [8]:
#Cantidad de paises diferentes
# Agrupamos por pais
paises=df_csv.groupby("pais")["pais"].count()
paises.count()

np.int64(164)

In [10]:
#Media de corrupción por año
df_csv.groupby("anio")["percepcion_corrupcion"].mean()

anio
2005    0.715875
2006    0.755737
2007    0.792069
2008    0.764120
2009    0.763371
2010    0.757199
2011    0.755170
2012    0.757945
2013    0.763475
2014    0.738347
2015    0.736524
2016    0.746677
2017    0.729197
2018    0.731744
Name: percepcion_corrupcion, dtype: float64

In [11]:
#Expectativa de vida por pais
df_csv.groupby("pais")["expectativa_vida"].mean()

pais
Afghanistán    52.254545
Albania        67.254545
Alemania       71.104616
Algeria        65.174286
Angola         53.550000
                 ...
Venezuela      65.829231
Vietnam        66.838462
Yemen          54.627273
Zambia         50.983333
Zimbabue       49.269231
Name: expectativa_vida, Length: 164, dtype: float64

In [17]:
#Archivo XML, lo cararemos como url_xml
url_xml="https://www.w3schools.com/xml/cd_catalog.xml"
df_xml=pd.read_xml(url_xml)

In [18]:
#Mostramos los primeros 6 registros
df_xml.head(6)

                 TITLE           ARTIST COUNTRY         COMPANY  PRICE  YEAR
0     Empire Burlesque        Bob Dylan     USA        Columbia   10.9  1985
1      Hide your heart     Bonnie Tyler      UK     CBS Records    9.9  1988
2        Greatest Hits     Dolly Parton     USA             RCA    9.9  1982
3  Still got the blues       Gary Moore      UK  Virgin records   10.2  1990
4                 Eros  Eros Ramazzotti      EU             BMG    9.9  1997
5       One night only         Bee Gees      UK         Polydor   10.9  1998

In [19]:
#Mostramos la informacion del archivo
df_xml.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26 entries, 0 to 25
Data columns (total 6 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   TITLE    26 non-null     object
 1   ARTIST   26 non-null     object
 2   COUNTRY  26 non-null     object
 3   COMPANY  26 non-null     object
 4   PRICE    26 non-null     float64
 5   YEAR     26 non-null     int64
dtypes: float64(1), int64(1), object(4)
memory usage: 1.3+ KB

In [20]:
#Tamaño del archivo
df_xml.shape

(26, 6)

In [21]:
#Filtramos los discos entre 1990 y 1997
df_xml_filtrado=df_xml[(df_xml["YEAR"] >= 1990) & (df_xml["YEAR"] <= 1997)]
df_xml_filtrado

,TITLE,ARTIST,COUNTRY,COMPANY,PRICE,YEAR
3,Still got the blues,Gary Moore,UK,Virgin records,10.2,1990
4,Eros,Eros Ramazzotti,EU,BMG,9.9,1997
7,Maggie May,Rod Stewart,UK,Pickwick,8.5,1990
8,Romanza,Andrea Bocelli,EU,Polydor,10.8,1996
10,Black angel,Savage Rose,EU,Mega,10.9,1995
12,For the good times,Kenny Rogers,UK,Mucik Master,8.7,1995
13,Big Willie style,Will Smith,USA,Columbia,9.9,1997
15,Soulsville,Jorn Hoel,Norway,WEA,7.9,1996
16,The very best of,Cat Stevens,UK,Island,8.9,1990
21,Pavarotti Gala Concert,Luciano Pavarotti,UK,DECCA,9.9,1991

In [25]:
#Disco mas viejo al mas reciente usando iloc con un db llamado df_xml_ordenado
df_xml_ordenado=df_xml.sort_values("YEAR")
#Mas viejo
df_xml_ordenado.iloc[0]

TITLE      The dock of the bay
ARTIST            Otis Redding
COUNTRY                    USA
COMPANY           Stax Records
PRICE                      7.9
YEAR                      1968
Name: 22, dtype: object

In [27]:
#Mas reciente
df_xml_ordenado.iloc[-1]

TITLE      1999 Grammy Nominees
ARTIST                     Many
COUNTRY                     USA
COMPANY                  Grammy
PRICE                      10.2
YEAR                       1999
Name: 11, dtype: object

In [28]:
#Cargamos el archivo excel como df_excel
url_excel="https://github.com/wantaprender-tech/Curso-Bigdata-Python/raw/refs/heads/main/Semana%20No.%201/base%20de%20datos%20excel%20tarea%20sem1.xlsx"
df_excel=pd.read_excel(url_excel)

In [30]:
#Mostramos los primeros 6 registros
df_excel.head(6)

,Empleado,Nombre del cliente,Ventas,Id de empleado,Id de producto,Id de cliente,Año,Mes,Producto,Cliente,Id de pedido,Fecha de pedido,Nombre del producto,Estado o provincia,País o región,Categoría
0,Francisco Chaves,Compañía AA,1400.0,9,34,27,2016,11,Cerveza Northwind Traders,Compañía AA,30,42696,Cerveza Northwind Traders,Madrid,España,Bebidas
1,Francisco Chaves,Compañía AA,105.0,9,80,27,2016,2,Ciruelas pasas Northwind Traders,Compañía AA,30,42417,Ciruelas pasas Northwind Traders,NV,Estados Unidos,Frutos secos
2,Luis Bonifaz,Compañía D,300.0,3,7,4,2016,10,Peras secas Northwind Traders,Compañía D,31,42647,Peras secas Northwind Traders,NY,Estados Unidos,Frutos secos
3,Luis Bonifaz,Compañía D,530.0,3,51,4,2016,7,Manzanas secas Northwind Traders,Compañía D,31,42577,Manzanas secas Northwind Traders,NY,Estados Unidos,Frutos secos
4,Luis Bonifaz,Compañía D,35.0,3,80,4,2016,1,Ciruelas pasas Northwind Traders,Compañía D,31,42377,Ciruelas pasas Northwind Traders,NY,Estados Unidos,Frutos secos
5,María Jesús Cuesta,Compañía L,270.0,4,1,12,2016,7,Té Chai Northwind Traders,Compañía L,32,42578,Té Chai Northwind Traders,Madrid,España,Bebidas

In [31]:
#Mostramos la información del archivo
df_excel.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6860 entries, 0 to 6859
Data columns (total 16 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Empleado             6860 non-null   object
 1   Nombre del cliente   6860 non-null   object
 2   Ventas               6860 non-null   float64
 3   Id de empleado       6860 non-null   int64
 4   Id de producto       6860 non-null   int64
 5   Id de cliente        6860 non-null   int64
 6   Año                  6860 non-null   int64
 7   Mes                  6860 non-null   int64
 8   Producto             6860 non-null   object
 9   Cliente              6860 non-null   object
 10  Id de pedido         6860 non-null   int64
 11  Fecha de pedido      6860 non-null   int64
 12  Nombre del producto  6860 non-null   object
 13  Estado o provincia   6860 non-null   object
 14  País o región        6860 non-null   object
 15  Categoría            6860 non-null   object
dtypes: float64(1), int64(7), object(8)
memory usage: 857.6+ KB

In [32]:
#Mostramos el tamaño del archivo
df_excel.shape

(6860, 16)

In [33]:
# Realizamos una copia del df original y eliminaremos la columna cliente
df_excel_copia=df_excel.copy()
df_excel_copia=df_excel_copia.drop(columns=['Producto','Cliente'])
#Primeros 6 registros
df_excel_copia.head(6)

,Empleado,Nombre del cliente,Ventas,Id de empleado,Id de producto,Id de cliente,Año,Mes,Id de pedido,Fecha de pedido,Nombre del producto,Estado o provincia,País o región,Categoría
0,Francisco Chaves,Compañía AA,1400.0,9,34,27,2016,11,30,42696,Cerveza Northwind Traders,Madrid,España,Bebidas
1,Francisco Chaves,Compañía AA,105.0,9,80,27,2016,2,30,42417,Ciruelas pasas Northwind Traders,NV,Estados Unidos,Frutos secos
2,Luis Bonifaz,Compañía D,300.0,3,7,4,2016,10,31,42647,Peras secas Northwind Traders,NY,Estados Unidos,Frutos secos
3,Luis Bonifaz,Compañía D,530.0,3,51,4,2016,7,31,42577,Manzanas secas Northwind Traders,NY,Estados Unidos,Frutos secos
4,Luis Bonifaz,Compañía D,35.0,3,80,4,2016,1,31,42377,Ciruelas pasas Northwind Traders,NY,Estados Unidos,Frutos secos
5,María Jesús Cuesta,Compañía L,270.0,4,1,12,2016,7,32,42578,Té Chai Northwind Traders,Madrid,España,Bebidas

In [36]:
#Ventas por vendedor
ventas_vendedor=df_excel_copia.groupby('Empleado')['Ventas'].sum()
ventas_vendedor

Empleado
Francisco Chaves         1658151.75
Humberto Acevedo          731728.50
Jesús Escolar             366450.00
Juan Carlos Rivas         892920.00
Luis Bonifaz              234021.00
María González            918540.00
María Jesús Cuesta        878920.00
Pilar Pinilla Gallego    1608053.75
Name: Ventas, dtype: float64

In [38]:
# Creamos totales por categoría
total_categoria=df_excel_copia.groupby('Categoría')['Ventas'].sum()

# Asignamos valores máximos y mínimos
categoria_min=total_categoria.idxmin()
categoria_max=total_categoria.idxmax()

# Resultados
print(categoria_min)
print(categoria_max)

Granos
Bebidas